idf_component_register(SRCS "task_xfer.c" "module_fram.c" "API_rtc.c" "task_rtc.c" "module_pcf8523.c" "task_pca.c" "module_pca9536.c" "module_i2c_bus.c" "system_sync.c" "system_diag.c" "system_queues.c" "system_faults.c" "system_state.c" "system_cfg.c" "main.c" "initialisation.c" "API_display.c" "API_pca.c" "task_log.c" "task_i2c.c"
                    INCLUDE_DIRS ".")
